const NoteActionTypes = {
  GET_ALL_NOTES: 'GET_ALL_NOTES',
  CREATE_NOTE: 'CREATE_NOTE',
  UPDATE_NOTE: 'UPDATE_NOTE',
  DELETE_NOTE: 'DELETE_NOTE',
  CLEAR_DATA: 'CLEAR_DATA',
  GET_ERRORS: 'GET_ERRORS',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  SET_SHOW_NOTE_DIALOG: 'SET_SHOW_PATIENT_DIALOG',
  UPLOAD_IMAGE: 'UPLOAD_IMAGE',
}

export default NoteActionTypes
